// <auto-generated />
using System;
using LHU_MaSV_NguyenVanTi.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LHU_MaSV_NguyenVanTi.Api.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.DangKyEntity", b =>
                {
                    b.Property<int>("DangKyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyId"));

                    b.Property<int>("LopHocPhanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DangKyId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("DangKy");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.Property<int>("LopHocPhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocPhanId"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("MaLopHP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MonHocId")
                        .HasColumnType("int");

                    b.Property<int>("NamHoc")
                        .HasColumnType("int");

                    b.Property<int>("SiSoToiDa")
                        .HasColumnType("int");

                    b.HasKey("LopHocPhanId");

                    b.HasIndex("MonHocId");

                    b.ToTable("LopHocPhan");

                    b.HasData(
                        new
                        {
                            LopHocPhanId = 1,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT101",
                            MonHocId = 1,
                            NamHoc = 2024,
                            SiSoToiDa = 45
                        },
                        new
                        {
                            LopHocPhanId = 2,
                            HocKy = 1,
                            MaLopHP = "24DTH02_IT101",
                            MonHocId = 1,
                            NamHoc = 2024,
                            SiSoToiDa = 45
                        },
                        new
                        {
                            LopHocPhanId = 3,
                            HocKy = 2,
                            MaLopHP = "24DTH01_IT102",
                            MonHocId = 2,
                            NamHoc = 2024,
                            SiSoToiDa = 40
                        },
                        new
                        {
                            LopHocPhanId = 4,
                            HocKy = 2,
                            MaLopHP = "24DTH02_IT102",
                            MonHocId = 2,
                            NamHoc = 2024,
                            SiSoToiDa = 40
                        },
                        new
                        {
                            LopHocPhanId = 5,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT103",
                            MonHocId = 3,
                            NamHoc = 2025,
                            SiSoToiDa = 35
                        },
                        new
                        {
                            LopHocPhanId = 6,
                            HocKy = 1,
                            MaLopHP = "24DTH02_IT103",
                            MonHocId = 3,
                            NamHoc = 2025,
                            SiSoToiDa = 35
                        },
                        new
                        {
                            LopHocPhanId = 7,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT104",
                            MonHocId = 4,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 8,
                            HocKy = 2,
                            MaLopHP = "24DTH01_IT105",
                            MonHocId = 5,
                            NamHoc = 2025,
                            SiSoToiDa = 40
                        },
                        new
                        {
                            LopHocPhanId = 9,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT106",
                            MonHocId = 6,
                            NamHoc = 2025,
                            SiSoToiDa = 45
                        },
                        new
                        {
                            LopHocPhanId = 10,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT107",
                            MonHocId = 7,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 11,
                            HocKy = 2,
                            MaLopHP = "24DTH02_IT107",
                            MonHocId = 7,
                            NamHoc = 2025,
                            SiSoToiDa = 50
                        },
                        new
                        {
                            LopHocPhanId = 12,
                            HocKy = 2,
                            MaLopHP = "24DTH01_IT108",
                            MonHocId = 8,
                            NamHoc = 2025,
                            SiSoToiDa = 40
                        },
                        new
                        {
                            LopHocPhanId = 13,
                            HocKy = 2,
                            MaLopHP = "24DTH02_IT108",
                            MonHocId = 8,
                            NamHoc = 2025,
                            SiSoToiDa = 40
                        },
                        new
                        {
                            LopHocPhanId = 14,
                            HocKy = 1,
                            MaLopHP = "24DTH01_IT109",
                            MonHocId = 9,
                            NamHoc = 2026,
                            SiSoToiDa = 45
                        },
                        new
                        {
                            LopHocPhanId = 15,
                            HocKy = 2,
                            MaLopHP = "24DTH01_IT110",
                            MonHocId = 10,
                            NamHoc = 2026,
                            SiSoToiDa = 40
                        });
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Property<int>("MonHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MonHocId"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTietLyThuyet")
                        .HasColumnType("int");

                    b.Property<int>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MonHocId");

                    b.ToTable("MonHoc");

                    b.HasData(
                        new
                        {
                            MonHocId = 1,
                            MaMon = "IT101",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Nhập môn lập trình"
                        },
                        new
                        {
                            MonHocId = 2,
                            MaMon = "IT102",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Kỹ thuật lập trình"
                        },
                        new
                        {
                            MonHocId = 3,
                            MaMon = "IT103",
                            SoTietLyThuyet = 45,
                            SoTinChi = 4,
                            TenMon = "Cấu trúc dữ liệu và giải thuật"
                        },
                        new
                        {
                            MonHocId = 4,
                            MaMon = "IT104",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            MonHocId = 5,
                            MaMon = "IT105",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Hệ quản trị cơ sở dữ liệu"
                        },
                        new
                        {
                            MonHocId = 6,
                            MaMon = "IT106",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Mạng máy tính"
                        },
                        new
                        {
                            MonHocId = 7,
                            MaMon = "IT107",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Lập trình hướng đối tượng"
                        },
                        new
                        {
                            MonHocId = 8,
                            MaMon = "IT108",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Phát triển ứng dụng Web"
                        },
                        new
                        {
                            MonHocId = 9,
                            MaMon = "IT109",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Phát triển ứng dụng di động"
                        },
                        new
                        {
                            MonHocId = 10,
                            MaMon = "IT110",
                            SoTietLyThuyet = 30,
                            SoTinChi = 3,
                            TenMon = "Kiểm thử phần mềm"
                        });
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.SinhVienEntity", b =>
                {
                    b.Property<int>("SinhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinhVienId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LopSinhHoat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("SinhVienId");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.DangKyEntity", b =>
                {
                    b.HasOne("LHU_MaSV_NguyenVanTi.Api.Database.Entities.LopHocPhanEntity", "LopHocPhan")
                        .WithMany("DangKies")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LHU_MaSV_NguyenVanTi.Api.Database.Entities.SinhVienEntity", "SinhVien")
                        .WithMany("DangKies")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.HasOne("LHU_MaSV_NguyenVanTi.Api.Database.Entities.MonHocEntity", "MonHoc")
                        .WithMany("LopHocPhans")
                        .HasForeignKey("MonHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.LopHocPhanEntity", b =>
                {
                    b.Navigation("DangKies");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.MonHocEntity", b =>
                {
                    b.Navigation("LopHocPhans");
                });

            modelBuilder.Entity("LHU_MaSV_NguyenVanTi.Api.Database.Entities.SinhVienEntity", b =>
                {
                    b.Navigation("DangKies");
                });
#pragma warning restore 612, 618
        }
    }
}
